{{- if .Values.artifacts.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-actions-artifacts
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: open-actions
    app.kubernetes.io/component: artifacts
automountServiceAccountToken: false
{{- end }}
