apiVersion: v1
kind: Service
metadata:
  name: open-actions-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: open-actions
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: open-actions
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      targetPort: webhook
      {{- with .Values.service.nodePort }}
      nodePort: {{ . }}
      {{- end }}
