controller:
  image:
    repository: ghcr.io/kelos-dev/open-actions-controller
    tag: latest
    pullPolicy: IfNotPresent
  githubAPIURL: https://api.github.com/
  githubServerURL: https://github.com
  actionCloneBaseURL: https://github.com

service:
  type: ClusterIP
  nodePort: null
