controller:
  image:
    repository: ghcr.io/kelos-dev/open-actions-controller
    tag: latest
    pullPolicy: IfNotPresent
  githubAPIURL: https://api.github.com/
  githubServerURL: https://github.com
  actionCloneBaseURL: ""
  workflowRunTTLSecondsAfterFinished: null

console:
  enabled: true
  replicas: 1
  publicURL: http://localhost:8080
  secretName: ""
  tokenKey: token
  image:
    repository: ghcr.io/kelos-dev/open-actions-console
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    nodePort: null

service:
  type: ClusterIP
  nodePort: null
