apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-actions-controller
spec:
  template:
    spec:
      containers:
        - name: manager
          imagePullPolicy: Never
          args:
            - --leader-elect=true
            - --github-api-url=http://github-fixture.open-actions-system.svc.cluster.local:8080/
            - --github-server-url=http://github-fixture.open-actions-system.svc.cluster.local:8080
            - --action-clone-base-url=http://github-fixture.open-actions-system.svc.cluster.local:8080
