controller:
  image:
    tag: e2e
  githubAPIURL: http://github-fixture.open-actions-system.svc.cluster.local:8080/
  githubServerURL: http://github-fixture.open-actions-system.svc.cluster.local:8080

console:
  publicURL: http://127.0.0.1:18082
  image:
    tag: e2e
    pullPolicy: Never
