apiVersion: actions.kelos.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: example-manual-deploy
  namespace: open-actions
spec:
  projectRef:
    name: default
  source:
    type: GitHub
    github:
      actor: octocat
      repository:
        id: 123456789
        owner: example
        name: project
      event:
        name: workflow_dispatch
        inputs:
          environment: staging
      revision:
        sha: 0123456789abcdef0123456789abcdef01234567
        ref: refs/heads/main
  workflowPath: .open-actions/workflows/deploy.yaml
