apiVersion: actions.kelos.dev/v1alpha1
kind: Runner
metadata:
  name: runner-1
  namespace: open-actions
spec:
  projectRef:
    name: default
  execution:
    image: ghcr.io/kelos-dev/open-actions-runner:latest
    imagePullPolicy: IfNotPresent
    env:
      - name: CACHE_URL
        value: https://cache.example
    resources:
      requests:
        cpu: "1"
        memory: 1Gi
      limits:
        cpu: "2"
        memory: 2Gi
  labels:
    - self-hosted
    - linux
    - x64
    - ubuntu-latest
