name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  confirm-first:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm first job
        run: echo "First Open Actions job is running"

  confirm-second:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm second job
        run: echo "Second Open Actions job is running"
